# -*- coding: utf-8 -*-
"""DAA2 2021.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KUDD7XS-p2TgTvK2RE-bxqGZ7fuEkgXD
"""

import numpy as np
print(np.__version__)
print("Hello, World!")
print("Nama saya (rajwa)")
print("NIM saya (2020071046)")

if 5>2:
    print("five is greater than two!")

x=5
y="john"
print(x)
print(y)

x=4
x="sally"
print(x)

def getLast(myList):
 return myList[-1]

print(getLast([1,2,3]))
print(getLast([1,2,3,4,5]))

def getKali(myList):
  Kali=2
  for item in myList:
      Kali=Kali*item
  return Kali

getKali([1,2,3,4])

def getBagi(myList):
  Bagi=50
  for item in myList:
      Bagi=Bagi/item
  return Bagi

getBagi([2,5])

def getSum(myList):
  sum=50
  for row in myList:
      for item in row:
          sum /= item
  return sum

getSum([[10],[2]])

def getSum(myList):
  sum=50
  for row in myList:
      for item in row:
          sum -= item
  return sum

getSum([[10,2],[2,2]])

def searchBinary(myList,item):
    first=0
    last=len(myList)-1
    foundFlag=False
    while( first<=last and not foundFlag):
      mid = (first+last)//2
      if myList[mid] == item :
        foundFlag = True
      else:
        if item < myList[mid]:
          last = mid - 1
        else:
          first = mid + 1
    return foundFlag

searchBinary([8,9,10,100,10000,2000,3000], 10)

searchBinary([8,9,10,100,10000,2000,3000], 5)